Use rsync "--link-dest" option instead of "cp --link" command
git-svn-id: svn+ssh://svn.osdn.jp/svnroot/hlbackup/debian/hlbackup/trunk@23 7c90d983-10fa-0310-8751-8832a4c28615

diff --git a/hlbackup b/hlbackup
--- a/hlbackup
+++ b/hlbackup
@@ -5,24 +5,15 @@
 LOGDIR=/var/log/hlbackup
 BASE=/backup
 TODAY=`date +%Y/%m/%d`
-RSYNC='/usr/bin/rsync -e ssh -avHS --numeric-ids --delete --delete-excluded'
+RSYNC='/usr/bin/rsync -e ssh -aqHS --numeric-ids --delete --delete-excluded'
 
 test -f /etc/default/hlbackup && . /etc/default/hlbackup
 
-backup_begin() {
-    local host=$1
+errormsg() {
+	local msg=$1
 
-    test -d ${BASE}/${host}/${TODAY} && return
-    if [ ! -d ${BASE}/${host}/latest ]; then
-        pushd ${BASE}/${host} > /dev/null
-        rm -f latest
-        ln -s `find -maxdepth 3 -type d -path "./????/??/??"  | sort -n | tail -1` latest
-        popd > /dev/null
-    fi
-    mkdir -p ${BASE}/${host}/${TODAY}
-    if [ -L ${BASE}/${host}/latest -a -d ${BASE}/${host}/latest ]; then
-        cp -a --link ${BASE}/${host}/latest/* ${BASE}/${host}/${TODAY}
-    fi
+	echo "backup failed: $msg" 1>&2
+	echo "backup failed: $msg" | logger -i -t backup -p local0.err
 }
 
 backup_end() {
@@ -35,31 +26,53 @@ backup_end() {
 }
 
 backup() {
-    local host=`echo $1 | sed -e 's/:.*//'`
-    logfile=$LOGDIR/$host/`basename $1`.log
-    src=$1
-    shift
+	local host=`echo $1 | sed -e 's/:.*//'`
+	logfile=$LOGDIR/$host/`basename $1`.log
+	src=$1
+	shift
 
-    backup_begin $host
-    mkdir -p `dirname $logfile`
-    savelog -m 0640 -u root -g adm -t $logfile > /dev/null
-    test "`hostname`" = "$host" && src=`echo $src | sed -e 's/^[^/]*//'`
-    echo "starting backup: $src" | logger -i -t backup -p local0.info
-    $RSYNC $src ${BASE}/${host}/${TODAY}/ $* > $logfile
-    if [ $? = 0 -o $? = 24 ]; then
-      backup_end $host
-      echo "backup completed: $src" | logger -i -t backup -p local0.info
-    else
-      echo "backup failed: $src" | logger -i -t backup -p local0.err
-    fi
+	# prepare backup
+	mkdir -p `dirname $logfile`
+	savelog -q -m 0640 -u root -g adm -t $logfile
+	test "`hostname`" = "$host" && src=`echo $src | sed -e 's/^[^/]*//'`
+	if [ ! -d $BASE/$host -o ! -w $BASE/$host ]; then
+		errormsg "$src: could not write to directory: $BASE/$host"
+		return
+	fi
+
+	# find "--link-dest" argument
+    if [ -d ${BASE}/${host}/latest/`basename $src` -a \
+	     ! ${BASE}/${host}/latest/`basename $src` -ef ${BASE}/${host}/${TODAY}/`basename $src` ]; then
+		linkdest="--link-dest=${BASE}/${host}/latest/`basename $src`"
+	else
+		linkdestdir=`find ${BASE}/${host} -maxdepth 3 -type d -path "${BASE}/${host}/????/??/??" | sort -n | tail -1`
+		if [ -n "$linkdestdir" -a \
+		     ! ${BASE}/${host}/latest/`basename $src` -ef $linkdestdir/`basename $src` ]; then
+			linkdest="--link-dest=$linkdestdir"
+		else
+			linkdest=""
+		fi
+	fi
+
+	# run backup
+	echo "starting backup: $src" | logger -i -t backup -p local0.info
+	$RSYNC --log-file=$logfile $linkdest $src ${BASE}/${host}/${TODAY}/ $*
+	if [ $? = 0 -o $? = 24 ]; then
+		backup_end $host
+		echo "backup completed: $src" | logger -i -t backup -p local0.info
+	else
+		errormsg $src | logger -i -t backup -p local0.err
+	fi
 }
 
 if [ -n "$1" ]; then
-    if echo "$1" | grep -vq :\/; then
-        echo "Usage: $0 hostname:/dirname" 1>&2
-        exit 1
-    fi
-    backup $*
+	if echo "$1" | grep -vq :\/; then
+		echo "Usage: $0 hostname:/dirname" 1>&2
+		exit 1
+	fi
+	backup $*
 else
     . /etc/hlbackup/run-backup
 fi
+
+# vim: set ts=4:sw=4:
